apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-home-confluence-int
  namespace: confluence-int
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn