apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluence-int
  namespace: argocd
spec:
  project: atlassian-int
  source:
    repoURL: https://github.com/nikolaypeshev-86/jira-int
    targetRevision: HEAD
    path: confluence/int
    helm:
      valueFiles:
        - values-int-argo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: confluence-int
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
