apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jira-int
  namespace: argocd
spec:
  project: atlassian-int
  source:
    repoURL: https://github.com/nikolaypeshev-86/jira-int   # points to your repo
    path: jira/int                                          # points to this directory in your repo
    targetRevision: HEAD                                    # or use a specific branch/commit
    helm:
      valueFiles:
        - values-int-argo.yaml                              # use this as your main values file
  destination:
    server: https://kubernetes.default.svc
    namespace: jira-int
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true