apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jira-int
  namespace: argocd
spec:
  project: atlassian-int
  source:
    repoURL: https://github.com/nikolaypeshev-86/jira-int
    targetRevision: HEAD
    path: jira/int
    helm:
      valueFiles:
        - values-int-helm.yaml
    chart: jira
    helmRepoURL: https://atlassian.github.io/data-center-helm-charts  
  destination:
    server: https://kubernetes.default.svc
    namespace: jira-int
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
