apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: confluence-pdb
  namespace: confluence-int
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: confluence
      