apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-home-prod
  namespace: jira-prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn