replicaCount: 1

updateStrategy:
  type: RollingUpdate

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi
    
jira:
  license: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: jira.int.catena-x.polygran.io
        paths:
          - path: /
            pathType: Prefix
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

postgresql:
  enabled: false

database:
  type: postgres72
  url: jdbc:postgresql://jira-db.int.svc.cluster.local:5432/jiradb
  credentials:
    secretName: jira-db-secret

sharedHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteOnce

localHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteOnce