replicaCount: 1

persistence:
  enabled: true

updateStrategy:
  type: RollingUpdate

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi
    
jira:
  mountSharedHome: true
  mountLocalHome: true
  sharedHomeMountPath: /var/atlassian/application-data/shared-home
  localHomeMountPath: /var/atlassian/application-data/jira  
  license: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: jira-int.catena-x.polygran.io
        paths:
          - path: /
            pathType: Prefix
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

postgresql:
  enabled: false

database:
  type: postgres72
  url: jdbc:postgresql://jira-db.int.svc.cluster.local:5432/jiradb
  credentials:
    secretName: jira-db-secret
    
volumes:
  localHome:
    mountPath: "/var/atlassian/application-data/jira"
    persistentVolumeClaim:
      create: true
      storageClassName: "longhorn"
  sharedHome:
    mountPath: "/var/atlassian/application-data/shared-home"
    persistentVolumeClaim:
      create: true
      storageClassName: "longhorn"

sharedHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteMany

localHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteOnce