

jira:
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 90
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 2
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10
  clustering:
    enabled: true
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10   
    memory: 8Gi
  persistence:
    enabled: true
  database:
    type: postgres72
    url: jdbc:postgresql://spdua20001d.corp.polygran.de:5432/jiradb-int-cluster
    credentials:
      secretName: jira-db-secret
  ingress:
      create: true
      nginx: true
      maxBodySize: 250m
      host: jira-int.catena-x.polygran.io
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"    
  volumes:
    localHome:
      persistentVolumeClaim:
        create: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 10Gi
    sharedHome:
      customVolume:
        persistentVolumeClaim:
          claimName: shared-home-int
          
