apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-home-int
  namespace: jira-int
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn