replicaCount: 1

jira:
  license: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: jira.int.catena-x.polygran.io
        paths:
          - path: /
            pathType: Prefix

postgresql:
  enabled: false

database:
  type: postgres72
  url: jdbc:postgresql://jira-db.int.svc.cluster.local:5432/jiradb
  credentials:
    secretName: jira-db-secret

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi