apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: jira
          image: atlassian/jira-software:9.4.9
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            - name: ATL_TOMCAT_PORT
              value: "8080"
            - name: JIRA_SHARED_HOME
              value: "/var/atlassian/application-data/shared-home"
          volumeMounts:
            - name: shared-home
              mountPath: /var/atlassian/application-data/shared-home
            - name: local-home
              mountPath: /var/atlassian/application-data/jira
      volumes:
        - name: shared-home
          persistentVolumeClaim:
            claimName: {{ printf "%s-shared-home" .Release.Name }}
        - name: local-home
          persistentVolumeClaim:
            claimName: {{ printf "%s-local-home" .Release.Name }}