

jira:
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 90
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 2
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10
  clustering:
    enabled: true
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10   
    memory: 8Gi
  persistence:
    enabled: true
  database:
    type: postgres72
    url: jdbc:postgresql://spdua20001d.corp.polygran.de:5432/jiradb-prod-cluster
    credentials:
      secretName: jira-db-secret
  ingress:
      create: true
      nginx: true
      maxBodySize: 250m
      host: jira-prod.catena-x.polygran.io
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"    
  volumes:
    localHome:
      persistentVolumeClaim:
        create: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi
    sharedHome:
      customVolume:
        persistentVolumeClaim:
          claimName: shared-home-prod
  additionalEnvironmentVariables:
  - name: JIRA_NODE_ID
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  additionalInitContainers:
    - name: generate-cluster-properties
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "jira.node.id=${JIRA_NODE_ID}" > /shared-config/cluster.properties
          echo "jira.shared.home=/var/atlassian/application-data/shared-home" >> /shared-config/cluster.properties
      env:
        - name: JIRA_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: cluster-properties
          mountPath: /shared-config

  additionalVolumes:
    - name: cluster-properties
      emptyDir: {}

  additionalVolumeMounts:
    - name: cluster-properties
      mountPath: /var/atlassian/application-data/jira