apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-shared-home" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "your-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: {{ toYaml .Values.sharedHome.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.sharedHome.size }}
  storageClassName: {{ .Values.sharedHome.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-local-home" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "your-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: {{ toYaml .Values.localHome.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.localHome.size }}
  storageClassName: {{ .Values.localHome.storageClassName }}