replicaCount: 1

updateStrategy:
  type: RollingUpdate

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi

confluence:
  license: ""  # add your license if needed
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - confluence.prod.catena-x.polygran.io
    tls:
      - hosts:
          - confluence.prod.catena-x.polygran.io
        secretName: confluence-prod-tls
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10


postgresql:
  enabled: false

database:
  type: postgres72
  url: jdbc:postgresql://confluence-db.prod.svc.cluster.local:5432/confluencedb
  credentials:
    secretName: confluence-db-secret

sharedHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteOnce

localHome:
  storageClassName: "longhorn"
  size: 10Gi
  accessModes:
    - ReadWriteOnce
